### ISSUE TITLE
buffer is not finite everywhere

### ISSUE THREAD

**Issue by zjFFFFFF** [itsuki8914/Voice-morphing-RelGAN#5]
Hello there,

`Traceback (most recent call last):
  File "train_relgan_vm.py", line 168, in <module>
    main()
  File "train_relgan_vm.py", line 163, in main
    sampling_rate)
  File "/home/developer/anaconda3/lib/python3.7/site-packages/librosa/output.py", line 223, in write_wav
    util.valid_audio(y, mono=False)
  File "/home/developer/anaconda3/lib/python3.7/site-packages/librosa/util/utils.py", line 170, in valid_audio
    raise ParameterError('Audio buffer is not finite everywhere')
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere`

I want to know why I got this error?Thank you.

**Comment by netuserjun** [comment]
> Hello there,
> 
> `Traceback (most recent call last): File "train_relgan_vm.py", line 168, in <module> main() File "train_relgan_vm.py", line 163, in main sampling_rate) File "/home/developer/anaconda3/lib/python3.7/site-packages/librosa/output.py", line 223, in write_wav util.valid_audio(y, mono=False) File "/home/developer/anaconda3/lib/python3.7/site-packages/librosa/util/utils.py", line 170, in valid_audio raise ParameterError('Audio buffer is not finite everywhere') librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere`
> 
> I want to know why I got this error?Thank you.

I also got the error.. 
Even I tried as the author did, It still makes that error.
Did you solve the error?
